### ISSUE TITLE
What tokenizer should be loaded?

### ISSUE THREAD

**Issue by hanswang1** [OptimalScale/DetGPT#3]
When I try the demo_detgpt.py after environment setup, I got below error:

(detgpt) admin@k8s:~/DetGPT$ python demo_detgpt.py --cfg-path configs/detgpt_tasktune_7b_coco.yaml
Initializing Chat
final text_encoder_type: bert-base-uncased
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Model loaded from /home/itadmin/.cache/huggingface/hub/models--ShilongLiu--GroundingDINO/snapshots/a94c9b567a2a374598f05c584e96798a170c56fb/groundingdino_swinb_cogcoor.pth
 => _IncompatibleKeys(missing_keys=[], unexpected_keys=['label_enc.weight'])
/home/itadmin/anaconda3/envs/detgpt2/lib/python3.9/site-packages/torch/cuda/__init__.py:104: UserWarning:
NVIDIA A100-PCIE-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA A100-PCIE-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
********************

loaded detector

Loading VIT
Loading VIT Done
Loading Q-Former
Loading Q-Former Done
Loading LLAMA
Traceback (most recent call last):
  File "/home/itadmin/hans/2d/DetGPT/demo_detgpt.py", line 198, in <module>
    model_llm = model_cls.from_config(model_config).to(cuda_llm)
  File "/home/itadmin/hans/2d/DetGPT/detgpt/models/detgpt.py", line 278, in from_config
    model = cls(
  File "/home/itadmin/hans/2d/DetGPT/detgpt/models/detgpt.py", line 95, in __init__
    self.llama_tokenizer = LlamaTokenizer.from_pretrained(llama_model, use_fast=False)
  File "/home/itadmin/anaconda3/envs/detgpt2/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1795, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for './output_models/vicuna-7b'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure './output_models/vicuna-7b' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.

**Comment by ardiya** [comment]
I have the same problem.
The download script doesn't download vicuna, so you need to download Meta's llama model and convert it to vicuna as explained in https://github.com/lm-sys/FastChat#vicuna-weights

**Comment by shizhediao** [comment]
Hi,
Thanks for your question and ardiya's reply!
The name `./output_models/vicuna-7b` is a placeholder. It is expected to prepare the vicuna weights and tokenizer by yourself first following the instruction ardiya provided.

Hope this helps.
Thank you again!
